services:
  zhbi:
    image: ${CONTAINER_IMAGE}:${CI_PIPELINE_ID}
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env.run
    volumes:
      - /opt/zhbi/data:/app/data
      - /opt/zhbi/Input:/app/Input
      - /opt/zhbi/uploads:/app/uploads

