import { open, screen, setFile, text, reload, mkxlsx, TAG, CONTRACT_HEAD, EX, SP, dbq, snap, sql, maxid, journal, changed, chk, summary, posts } from "./hx.mjs";
const IMP = "/import-contracting-xlsx";
const F1 = mkxlsx("br1.xlsx", CONTRACT_HEAD, [["АО «Заказчик»", "ООО «Тест-Браузер»", `BR1-${TAG} от 03.09.2026`, "1 от 04.09.2026", "Кв5", 2]], "Контрактация");
const F2 = mkxlsx("br2.xlsx", CONTRACT_HEAD, [["АО «Заказчик»", "ООО «Тест-Браузер»", `BR2-${TAG} от 03.09.2026`, "1 от 04.09.2026", "Кв6", 4]], "Контрактация");
const F3 = mkxlsx("br3.xlsx", CONTRACT_HEAD, [["АО «Заказчик»", "ООО «Тест-Браузер»", `BR3-${TAG} от 03.09.2026`, "1 от 04.09.2026", "Кв5", 1]], "Контрактация");
const b = await open("admin");
await screen(b, "contracting-import");
const sel = (v) => b.eval(`(()=>{const s=document.querySelector('#ex-object');s.value=${JSON.stringify(String(v))};s.dispatchEvent(new Event('input',{bubbles:true}));return s.value})()`);
const st = () => text(b, "#ex-status");
const submit = async () => { await b.clickSel("#ex-go"); };
const dialog = () => b.eval(`(()=>{const d=document.querySelector('.v2-dialog');return d?d.innerText:null})()`);
console.log("== клиентская проверка файла (запросов быть не должно)");
await sel(2);
await submit(); await b.sleep(300);
chk((await st()).includes("Сначала выберите файл"), "без файла: " + (await st()));
await setFile(b, "#ex-file", EX + "/note.txt"); await submit(); await b.sleep(300);
chk((await st()).includes(".xlsx"), "не xlsx: " + (await st()));
await setFile(b, "#ex-file", EX + "/empty.xlsx"); await submit(); await b.sleep(300);
chk((await st()).includes("пуст"), "пустой файл: " + (await st()));
await setFile(b, "#ex-file", EX + "/big.xlsx"); await submit(); await b.sleep(300);
chk((await st()).includes("200 МБ"), "файл 201 МБ: " + (await st()));
chk(posts(b, IMP).length === 0, "клиентские отказы не отправили ни одного запроса");
console.log("== серверный отказ на битом файле: ввод остаётся, кнопка снова доступна");
await setFile(b, "#ex-file", EX + "/bad_zip.xlsx"); await submit();
await b.waitFor(`document.querySelector('.v2-dialog')`, 5000);
await b.clickSel('[data-choice="confirm"]');
await b.waitFor(`document.querySelector('#ex-status').className.includes('bad')`, 10000);
chk((await st()).includes("повреждён"), "422 показан текстом сервера: " + (await st()));
chk(await b.eval(`document.querySelector('#ex-file').files.length===1 && !document.querySelector('#ex-go').disabled`), "файл выбран и кнопка доступна после ошибки");
chk(posts(b, IMP).length === 1, "на битый файл ушёл один запрос");
console.log("== успех: двойной щелчок по кнопке → один запрос");
const s0 = snap(), j0 = maxid();
await setFile(b, "#ex-file", F1);
const r = await b.rect("#ex-go");
await b.click(r.cx, r.cy, { count: 2 });   // второй щелчок двойного клика попадает на подложку диалога = отмена (безопасно)
await b.sleep(600);
chk(posts(b, IMP).length === 1 && !(await dialog()), "двойной щелчок по кнопке: диалог закрыт подложкой, второго запроса нет");
// задержка ответа, чтобы успеть нажать кнопку повторно, пока запрос в пути
await b.eval(`(()=>{const orig=window.fetch; window.fetch=async(...a)=>{if(String(a[0]).includes('/import-contracting-xlsx')) await new Promise(r=>setTimeout(r,1800)); return orig(...a);}})()`);
await b.clickSel("#ex-go");
await b.waitFor(`document.querySelector('.v2-dialog')`, 5000);
const dlg = await dialog();
chk(dlg.includes("br1.xlsx") && dlg.includes("Объект-2") && dlg.includes("копию базы"), "диалог подтверждения называет файл, объект и последствия");
await b.shot(SP + "/exchange_work/s_contr_confirm.png");
await b.clickSel('[data-choice="confirm"]');
await b.sleep(300);
chk(await b.eval(`document.querySelector('#ex-go').disabled`), "пока запрос в пути, кнопка «Импортировать» заблокирована");
await b.clickSel("#ex-go"); await b.key("Enter"); await b.sleep(200);
await b.waitFor(`document.querySelector('#ex-status').className.includes('ok')`, 20000);
chk(posts(b, IMP).length === 2, `повторные нажатия во время запроса: на успешный файл ушёл один запрос (всего POST: ${posts(b, IMP).length})`);
chk(posts(b, IMP).at(-1).url.endsWith("object_id=2"), "object_id=2 в адресе");
chk((await text(b, "#ex-result")).includes("Позиций создано"), "результат показан: " + (await text(b, "#ex-result")).replace(/\n/g, " ").slice(0, 120));
await b.shot(SP + "/exchange_work/s_contr_result.png");
await b.sleep(1800);
const s1 = snap();
chk(changed(s0, s1).includes("contracts") && changed(s0, s1).includes("contract_lines"), "в БД изменились контракты и позиции: " + changed(s0, s1).join(","));
chk(sql(`select count(*) n from agreements where number='BR1-${TAG}'`)[0].n === 1, "договор BR-1 создан в БД");
const ev = journal("import_contracting", j0);
chk(ev.length === 1, "в журнале ровно одно событие import_contracting");
console.log("== после перезагрузки страницы результат на месте (и в V1)");
await b.goto("http://127.0.0.1:8150/v2#/contracts"); await b.sleep(1500);
const via = await b.eval(`fetch('/contracts').then(r=>r.json()).then(l=>l.some(c=>c.agreement_number==='BR1-${TAG}'))`);
chk(via === true, "GET /contracts после перезагрузки содержит BR-1");
await b.goto("http://127.0.0.1:8150/?ui=v1"); await b.sleep(3500);
const v1 = await b.eval(`document.title + ' | ' + (typeof state!=='undefined' && state.currentUser ? 'вошёл' : 'нет')`);
chk(!b.exceptions.length, "V1 открылся без исключений: " + v1 + " " + JSON.stringify(b.exceptions.slice(0, 2)));
const v1list = await b.eval(`(async()=>{document.getElementById('menu-contracts')&&document.getElementById('menu-contracts').click(); await new Promise(r=>setTimeout(r,1500)); return document.getElementById('contracts-list').innerText.includes('BR1-${TAG}')})()`);
chk(v1list === true, "в V1 в списке контрактов виден BR-1");
console.log("== неизвестный исход: ответ потерян, запрос выполнен");
await reload(b, "#/contracting-import");
await b.eval(`(()=>{const orig=window.fetch; window.__n=0; window.fetch=async(...a)=>{const r=await orig(...a); if(String(a[0]).includes('/import-contracting-xlsx')){window.__n++; throw new TypeError('Failed to fetch');} return r;}})()`);
await sel(2);
const nBefore = posts(b, IMP).length; const j1 = maxid();
await setFile(b, "#ex-file", F2); await submit();
await b.waitFor(`document.querySelector('.v2-dialog')`, 5000); await b.clickSel('[data-choice="confirm"]');
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 15000);
chk((await st()).includes("Результат неизвестен"), "показано «Результат неизвестен»");
await b.sleep(1500);
chk(await b.eval("window.__n") === 1, "запрос не повторялся автоматически (ушёл один)");
await b.clickSel('#ex-status [data-verify]');
await b.waitFor(`document.querySelector('[data-verify-out]').innerText.includes('выполнена')`, 8000);
chk((await text(b, "[data-verify-out]")).includes("Операция выполнена"), "сверка по журналу: операция выполнена → " + (await text(b, "[data-verify-out]")).replace(/\n/g, " ").slice(0, 160));
chk(sql(`select count(*) n from agreements where number='BR2-${TAG}'`)[0].n === 1, "в БД договор BR-2 действительно создан");
console.log("== неизвестный исход: запрос не дошёл (offline)");
await reload(b, "#/contracting-import");
await sel(2);
const s2 = snap();
await setFile(b, "#ex-file", F3); await submit();
await b.waitFor(`document.querySelector('.v2-dialog')`, 5000);
await b.offline(true); await b.clickSel('[data-choice="confirm"]');
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 15000);
await b.offline(false); await b.sleep(500);
await b.clickSel('#ex-status [data-verify]');
await b.waitFor(`document.querySelector('[data-verify-out]').innerText.length>40`, 8000);
chk((await text(b, "[data-verify-out]")).includes("нет"), "сверка: события после отправки нет → " + (await text(b, "[data-verify-out]")).replace(/\n/g, " ").slice(0, 160));
await b.sleep(1500);
chk(JSON.stringify(snap()) === JSON.stringify(s2), "offline: БД не изменена");
console.log("== откат (409 стража) в интерфейсе");
await reload(b, "#/contracting-import");
await sel(1);
const s3 = snap(), j3 = maxid();
await setFile(b, "#ex-file", EX + "/contr_rollback.xlsx"); await submit();
await b.waitFor(`document.querySelector('.v2-dialog')`, 5000); await b.clickSel('[data-choice="confirm"]');
await b.waitFor(`document.querySelector('#ex-status').className.includes('bad')`, 20000);
chk((await st()).includes("ниже уже привязанного"), "409 текстом сервера: " + (await st()).slice(0, 140));
await b.sleep(1800);
chk(JSON.stringify(snap()) === JSON.stringify(s3), "откат: БД не изменена");
chk(journal("import_contracting", j3).length === 0, "откат: события в журнале нет");
chk(!b.exceptions.length, "исключений страницы нет: " + JSON.stringify(b.exceptions.slice(0, 2)));
summary();
await b.close();
