import { clk, open, screen, setFile, text, reload, mkxlsx, TAG, EX, SP, snap, sql, maxid, journal, chk, summary, posts } from "./hx.mjs";
const b = await open("admin");
const confirmDlg = async () => { await b.waitFor(`document.querySelector('.v2-dialog')`, 5000); const t = await text(b, ".v2-dialog"); await b.clickSel('[data-choice="confirm"]'); return t; };
const lose = (sub) => b.eval(`(()=>{const o=window.fetch; window.fetch=async(...a)=>{const r=await o(...a); if(String(a[0]).includes(${JSON.stringify(sub)})) throw new TypeError('Failed to fetch'); return r;}})()`);
const sel = (id, v) => b.eval(`(()=>{const s=document.querySelector(${JSON.stringify(id)});s.value=${JSON.stringify(String(v))};s.dispatchEvent(new Event('input',{bubbles:true}));return s.value})()`);
console.log("== график: двойной щелчок, offline, потерянный ответ");
const HEAD = ["Тип и Подтип", "Начало", "Окончание", "Кран", "Захватка", "Стоянка", "Этаж"];
const sched = mkxlsx("br2_sched.xlsx", HEAD, [["Колонна верхняя", "Пн 12.10.26", "Пт 16.10.26", "Кран 1", "Захватка 1", "Стоянка 01", "7 этаж"]], "График СМР");
await reload(b, "#/schedule-import"); await sel("#ex-object", 2); await setFile(b, "#ex-file", sched);
const r = await b.rect("#ex-go"); await b.click(r.cx, r.cy, { count: 2 }); await b.sleep(500);
chk(posts(b, "/import-schedule-xlsx").length === 0, "двойной щелчок по кнопке: диалог закрыт подложкой, запроса нет");
const s0 = snap();
await clk(b, "#ex-go"); await b.waitFor(`document.querySelector('.v2-dialog')`, 5000);
await b.offline(true); await b.clickSel('[data-choice="confirm"]');
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 15000); await b.offline(false); await b.sleep(400);
chk((await text(b, "#ex-status")).includes("Результат неизвестен"), "offline: «Результат неизвестен»");
chk(JSON.stringify(snap()) === JSON.stringify(s0), "offline: БД не менялась");
await reload(b, "#/schedule-import"); await sel("#ex-object", 2); await setFile(b, "#ex-file", sched);
await lose("/import-schedule-xlsx"); const n0 = posts(b, "/import-schedule-xlsx").length, j0 = maxid();
await clk(b, "#ex-go"); await confirmDlg();
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 30000); await b.sleep(1500);
chk(posts(b, "/import-schedule-xlsx").length === n0 + 1, "потерянный ответ: без автоповтора");
await b.clickSel('#ex-status [data-verify]'); await b.waitFor(`document.querySelector('[data-verify-out]').innerText.includes('выполнена')`, 10000);
chk(true, "сверка по журналу: график загружен");
console.log("== восстановление статусов: потерянный ответ");
const HH = ["DXF handle", "Марка", "Статус", "Статус изменён", "Кто изменил", "Комментарий"];
const pl = sql("select id, dxf_handle, mark from elements where source_file='Чертёж-4.dxf' and is_current=1 and current_status='planned' and mark not in ('Кв5','Кв6') order by id limit 2");
const hs = mkxlsx("br2_restore.xlsx", HH, [[pl[0].dxf_handle, pl[0].mark, "Отгружен", "2026-10-07 09:00:00", "Тест В2", null]], "Статус на дату");
await reload(b, "#/status-restore"); await sel("#ex-object", 2); await setFile(b, "#ex-file", hs);
await lose("/import-history-xlsx");
await clk(b, "#ex-go"); await confirmDlg();
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 30000);
await b.clickSel('#ex-status [data-verify]'); await b.waitFor(`document.querySelector('[data-verify-out]').innerText.includes('выполнена')`, 10000);
chk(sql(`select current_status from elements where id=${pl[0].id}`)[0].current_status === "shipped", "восстановление: статус «Отгружен» действительно записан, сверка это показала");
console.log("== справочник объектов: потерянный ответ на применение");
const OH = ["Наименование ОС", "Адрес", "СМУ", "Директор СМУ", "ДП / РП", "Статус ОС", "Широта", "Долгота", "Фото/Видео", "Старт СМР"];
const NAME = `Тест-В2 потеря ${TAG}`;
const of = mkxlsx("br2_obj.xlsx", OH, [[NAME, null, null, null, null, "Активный", null, null, null, null]], "Объекты на карте");
await reload(b, "#/objects-import"); await setFile(b, "#ex-file", of); await clk(b, "#ex-analyze"); await b.waitFor(`document.querySelector('#ex-table table')`, 20000);
await lose("/objects-import/apply");
await clk(b, "#ex-apply"); await confirmDlg();
await b.waitFor(`document.querySelector('#ex-status [data-verify]')`, 30000);
await b.clickSel('#ex-status [data-verify]'); await b.waitFor(`document.querySelector('[data-verify-out]').innerText.includes('выполнена')`, 10000);
chk(sql(`select count(*) n from objects where name='${NAME}'`)[0].n === 1, "объект создан, сверка по журналу это показала");
// уход с несохранённой сверкой
await reload(b, "#/objects-import"); await setFile(b, "#ex-file", mkxlsx("br2_obj2.xlsx", OH, [[`Тест-В2 уход ${TAG}`, null, null, null, null, "Активный", null, null, null, null]], "Объекты на карте"));
await clk(b, "#ex-analyze"); await b.waitFor(`document.querySelector('#ex-table table')`, 20000);
await b.eval(`document.querySelector('#v2-side [data-section="home"]').click()`); await b.sleep(600);
chk((await text(b, ".v2-dialog")).includes("не применена"), "уход с неприменённой сверкой: диалог «Уйти?»");
await b.clickSel('[data-choice="cancel"]'); await b.sleep(300);
chk((await b.eval(`document.querySelector('#v2-content h2')?.innerText`)).includes("Загрузка справочника объектов"), "«Остаться»: экран на месте");
chk(!b.exceptions.length, "исключений нет: " + JSON.stringify(b.exceptions.slice(0, 2)));
summary(); await b.close();
