import { clk, open, screen, setFile, text, reload, mkbulk, TAG, EX, SP, snap, sql, maxid, journal, chk, summary, posts } from "./hx.mjs";
const b = await open("admin");
await screen(b, "bulk-edit");
const st = () => text(b, "#bk-status");
const confirmDlg = async () => { await b.waitFor(`document.querySelector('.v2-dialog')`, 5000); const t = await b.eval(`document.querySelector('.v2-dialog').innerText`); await b.clickSel('[data-choice="confirm"]'); return t; };
console.log("== режим «Контрактация»");
const ic = mkbulk("contracting", "bk_contr.xlsx");
await b.eval(`document.querySelector('#bk-modes [data-mode="contracting"]').click()`);
chk((await text(b, "#bk-scope")).includes("Все позиции всех контрактов"), "для контрактации выбора объекта нет");
await setFile(b, "#bk-file", EX + "/bk_contr.xlsx"); await clk(b, "#bk-analyze");
await b.waitFor(`document.querySelector('#bk-table table')`, 30000);
chk((await st()).includes("Расхождений: 1"), "сверка контрактации: " + (await st()));
chk((await text(b, "#bk-table")).includes("Тема"), "в таблице поле «Тема контракта»");
const j0 = maxid();
await clk(b, "#bk-apply"); await confirmDlg();
await b.waitFor(`document.querySelector('#bk-status').innerText.includes('Готово')`, 30000);
chk((await text(b, "#bk-result")).includes("Позиций"), "результат: " + (await text(b, "#bk-result")).replace(/\n/g, " ").slice(0, 100));
chk(sql(`select count(*) n from contracts where theme like 'тема ${TAG}%'`)[0].n === 1, "тема контракта записана в БД");
await b.sleep(1800);
chk(journal("contracting_bulk_edit", j0).length === 1, "журнал: contracting_bulk_edit");
console.log("== назначение контракта запланированному изделию (дата статуса)");
await reload(b, "#/bulk-edit");
const ia = mkbulk("assign", "bk_assign.xlsx");
await setFile(b, "#bk-file", EX + "/bk_assign.xlsx"); await clk(b, "#bk-analyze");
await b.waitFor(`document.querySelector('#bk-table table')`, 30000);
chk((await text(b, "#bk-table")).includes("статус «Контрактация»"), "в таблице пометка «+ статус «Контрактация»»");
chk(!(await b.eval(`document.querySelector('#bk-datebox').hidden`)), "поле даты статуса показано");
const nAp = posts(b, "/bulk-edit/apply").length;
await clk(b, "#bk-apply"); await b.sleep(400);
chk((await st()).includes("Укажите дату статуса"), "без даты применение не идёт: " + (await st()).slice(0, 80));
chk(!(await b.eval(`!!document.querySelector('.v2-dialog')`)) && posts(b, "/bulk-edit/apply").length === nAp, "запрос не отправлен, диалога нет");
await b.eval(`(()=>{const i=document.querySelector('#bk-date');i.value='2026-10-06';i.dispatchEvent(new Event('input',{bubbles:true}))})()`);
await clk(b, "#bk-apply"); const d = await confirmDlg();
chk(d.includes("добавят изделию статус «Контрактация» на 2026-10-06"), "подтверждение называет дату статуса");
await b.waitFor(`document.querySelector('#bk-status').innerText.includes('Готово')`, 30000);
const rowDb = sql(`select current_status, contract_id from elements where id=${ia.id}`)[0];
chk(rowDb.current_status === "contracting" && rowDb.contract_id, "в БД статус «Контрактация» и контракт назначены");
chk(JSON.parse(posts(b, "/bulk-edit/apply").at(-1).body).contracting_date === "2026-10-06", "в теле запроса дата статуса");
chk(sql(`select count(*) n from status_history where element_id=${ia.id} and status='contracting'`)[0].n === 1, "в истории элемента одна запись «Контрактация»");
await b.goto("http://127.0.0.1:8150/?ui=v1"); await b.sleep(3500);
chk(!b.exceptions.length, "V1 открывается без исключений");
summary();
await b.close();
